### ISSUE TITLE
Upgrading to v6.0.0 remove the `toBeInTheDocument` interface with vitest

### ISSUE THREAD

**Issue by qchuchu** [testing-library/jest-dom#515]
- `@testing-library/jest-dom` version: 6.0.0
- `node` version: 18.16
- `npm` (or `yarn`) version: 9.5.1

### Relevant code or config:

```ts
import '@testing-library/jest-dom/vitest';
import { vitest } from 'vitest';
```

```ts
  await waitFor(() => {
    expect(getByTestId('text-input-error-message')).toBeInTheDocument();
  });
```

### What you did:

Upgraded from v5 to v6

### What happened:

<img width="654" alt="image" src="https://github.com/testing-library/jest-dom/assets/45853629/8972b20b-de1a-46a5-a2b3-267cbd55322f">

I don't know why, but upgrading the package to the last version using vitest caused all my "toBeInTheDocument" matchers to be undefined, although I can see them in the type definition of the package.

### Reproduction:

TO-DO

### Problem description:

- All my tests are failing because toBeInTheDocument is not defined anymore

### Suggested solution:

I guess this is due to an upgrade on the dependency of jest types but I'm not sure. Still digging.

**Comment by jgoz** [comment]
What version of vitest, and where is the import statement located for @testing-library/jest-dom/vitest?

**Comment by curtvict** [comment]
fwiw this is happening to me in Jest too.

**Comment by qchuchu** [comment]
ah sorry I thought that I added the vitest version.

Vitest -> 0.34.2

I added the import statement in the vitest.setup.ts file (that is pointed from my vite.config.ts like this) 

```ts
/// <reference types="vitest" />

import react from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['test/vitest.setup.ts'],
    include: ['**/?(*.)test.ts?(x)'],
  },
});
```

**Comment by qchuchu** [comment]
So it does work by adding the setup file in the tsconfig.json, but only if I stay with the original configuration

`test/vitest.setup.ts`
```ts
import '@testing-library/jest-dom';
```

If I add /vitest at the end, i'm facing the issue anymore.

**Comment by jgoz** [comment]
Hmm, I think that's because you're using Vitest in "globals" mode. There isn't really a difference between what you have now and using `/vitest`, which was designed for the default non-globals mode, so if this works for you I say go with it.

**Comment by Meemaw** [comment]
Getting this error trying to import

// setup.ts
```js
import matchers from '@testing-library/jest-dom/vitest';
```

```sh
File '/Users/x/y/node_modules/@testing-library/jest-dom/vitest.d.ts' is not a module.ts(2306)
```

**Comment by dominikg** [comment]
is adding the setup file to the tsconfig the only way to get this to work?
I'm using a monorepo where the vitest config is created in a separate package and the consuming applications/libraries have it like this in their vitest.config.ts

```js
import {defineVitestConfig} from 'shared-workspace-vitest-setup';
export default defineVitestConfig({
  // custom options here that get merged with the default config
  // default config contains a setupFile adding dom matchers
});
```

i don't really want to add something like `../../packages/vitest-config/setupFile.js` to every package tsconfig just for this, if that even works because the file is outside of the tsconfig parent dir....

**Comment by jgoz** [comment]
@dominikg Thanks for pointing out the alternate ways of getting the types recognized by TS. We should probably add that to the readme.

**Comment by DeveloperMatheus** [comment]
> fwiw this is happening to me in Jest too.

I can also confirm this is also happening with Jest as well. Don't know how to handle those errors yet :(

**Comment by jgoz** [comment]
For those using Jest, make sure you are importing like this:

```
import '@testing-library/jest-dom'
```

Many people are using an older deprecated `/extend-expect` import that was removed in v6.

**Comment by curtvict** [comment]
Thanks @jgoz I can confirm this fixes the issue for me.

**Comment by DeveloperMatheus** [comment]
@jgoz Sorry for asking help in this issue, i was checking my setup files and i see that i'm importing almost the same way as the library's documentation:

I have a .setup folder that groups some mocks globally, and also the `import '@testing-library/jest-dom`.
This is my `setupFilesAfterEnv` property in jest.config.js:
`setupFilesAfterEnv: ['<rootDir>/.jest/setup.ts']`

You have any suggestion of what might be causing my errors? When i'm importing on each test, the errors goes away (of course this is a solution, but would be better for me importing this globally in the setup hehe)

**Comment by jgoz** [comment]
@DeveloperMatheus Is your setup file included in tsconfig.json? Like, in the `includes` or `files` properties?

**Comment by DeveloperMatheus** [comment]
@jgoz Many many many thanks for your help! It worked!

**Comment by kalvenschraut** [comment]
I think depending on how you import expect may cause this issue to occur. For instance my import looks like

```ts
import { expect } from 'vitest';
```

and below is a SS of what the type def points to
![image](https://github.com/testing-library/jest-dom/assets/30308012/a7bf4c4a-aec8-4152-a9d4-5567911cf34c)

instead of the above if I do
![image](https://github.com/testing-library/jest-dom/assets/30308012/6a3f04e0-840a-4555-a91c-db6aeb11d30c)
then typescript finds the functions defined by jest-dom. Not sure if both need to be defined depending on how expect is being imported by the user?

**Comment by ajnozari** [comment]
So while adding `import '@testing-library/jest-dom';` to my setup for vitest (0.34.3) does prevent TS from giving an error, removing it gives me a slightly different error:  

```
Property  toBeInTheDocument  does not exist on type  Assertion<HTMLElement>
```

**Comment by jgoz** [comment]
```ts
import '@testing-library/jest-dom/vitest';
```

**Comment by jgoz** [comment]
And `setupTests.ts` is included in your tsconfig.json file, either via `include` or `files`?

**Comment by justinwaite** [comment]
Also using pnpm, I'm getting the type error `Property  toBeInTheDocument  does not exist on type  Assertion<HTMLElement> `. 

The tests pass, but still get the typescript error when typechecking.

setupTests.ts:
```
import { installGlobals } from '@remix-run/node';
import '@testing-library/jest-dom/vitest';

installGlobals();
```

tsconfig includes `setupTests.ts` explicitly

**Comment by DylanP97** [comment]
Hi,
Try to roll back to 5.16.5 version for @testing-library/jest-dom
npm i -D @testing-library/jest-dom@5.16.5

**Comment by dteoh** [comment]
Hey guys, I also ran into the same issue but finally got a working setup with v6.1.3 and pnpm. I have a React project created by Vite.

My setup:

```ts
// src/__tests__/extend-expect.ts
import "@testing-library/jest-dom/vitest";
```

```ts
// src/vitest.d.ts
import { type TestingLibraryMatchers } from "@testing-library/jest-dom/matchers";
import {
  type Assertion,
  type AsymmetricMatchersContaining,
  type expect,
} from "vitest";

type CustomMatchers<R = unknown> = TestingLibraryMatchers<
  ReturnType<typeof expect.stringContaining>,
  R
>;

declare module "vitest" {
  interface Assertion<T = unknown> extends CustomMatchers<T> {}
  interface AsymmetricMatchersContaining extends CustomMatchers {}
}

```

For `tsconfig.json`, there were no additional changes. I did not add the extend-expect file into `include` (Vite already added `src` dir).

I think the problem is that the types being shipped for `@testing-library/jest-dom/vitest` just doesn't match with Vitest's own official docs of how to extend the types.

**Comment by Ridd0** [comment]
To make it work if you are using the vitest:
1. Make sure you have installed `@testing-library/jest-dom`
2. Create the `setupTests.ts` file with content inside `import '@testing-library/jest-dom/vitest'`
3. Import the `setupTests.ts` file inside `vitest.config.ts`, for example: `setupFiles: path.resolve(__dirname, '../../setupTests.ts'),`
4. Add `"files": ["../../setupTests.ts"]` into the `tsconfig.json` file

**Comment by nwi-di** [comment]
> So it does work by adding the setup file in the tsconfig.json, but only if I stay with the original configuration
> 
> `test/vitest.setup.ts`
> 
> ```ts
> import '@testing-library/jest-dom';
> ```
> 
> If I add /vitest at the end, i'm facing the issue again.

Had the same issue and can confirm this. When having "globals" set to `true` (in `vite.config.ts`), I need to import from `@testing-library/jest-dom` instead of `@testing-library/jest-dom/vitest` to make TypeScript happy.

But after taking a look into docs from vitest config for [globals](https://vitest.dev/config/#globals), I saw that you need to add `vitest/globals` to `compilerOptions\types` property. I did not had that and added it now. With that the import from `@testing-library/jest-dom/vitest` works without troubles

**Comment by mdodge-ecgrow** [comment]
> > So it does work by adding the setup file in the tsconfig.json, but only if I stay with the original configuration
> > `test/vitest.setup.ts`
> > ```ts
> > import '@testing-library/jest-dom';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I add /vitest at the end, i'm facing the issue again.
> 
> Had the same issue and can confirm this. When having "globals" set to `true` (in `vite.config.ts`), I need to import from `@testing-library/jest-dom` instead of `@testing-library/jest-dom/vitest` to make TypeScript happy.
> 
> But after taking a look into docs from vitest config for [globals](https://vitest.dev/config/#globals), I saw that you need to add `vitest/globals` to `compilerOptions\types` property. I did not had that and added it now. With that the import from `@testing-library/jest-dom/vitest` works without troubles

Thank you!!  I can confirm this also worked for me!

**Comment by matchatype** [comment]
Just bumped in this issue. For me, after following the setup instructions found on the [testing-library docs](https://testing-library.com/docs/svelte-testing-library/setup/#vitest), I also had to add jsdom types: `npm i -D @types/testing-library__jest-dom`, then it worked.

**Comment by vnaykvkrm** [comment]
create a setupTest.ts file in src folder and  add `import '@testing-library/jest-dom'`

In vitest.config.ts file
```
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

```
export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/setupTests.ts'],
    coverage: {
      provider: 'v8'
    }
  }
})
```
```

And finally install types/testing-library. This worked for me

**Comment by ecoms-ye** [comment]
```ts
/// <reference types="@testing-library/jest-dom" />

// https://github.com/testing-library/jest-dom?tab=readme-ov-file#with-vitest
// https://github.com/testing-library/jest-dom/issues/515
import '@testing-library/jest-dom/vitest'
```

**Comment by RinalinDS** [comment]
"@testing-library/jest-dom": "^6.4.2",
 "@testing-library/react": "^14.2.2",
 "vitest": "^1.4.0"
 
 i have  one project create with next.js
 and it was enough to create a setup.ts and add vitest.config setupFiles
 But in second project which started with vite i have identical versions as above and this approach didn't work
 i have to manually create global.d.ts with :
 ```import '@testing-library/jest-dom';

declare global {
  namespace jest {
    interface Matchers<R> {
      toBeInTheDocument(): R;
      // Add other custom matchers here as needed
    }
  }
}
```

can't tell why it worked in first , but didn't in second

**Comment by curtvict** [comment]
@RinalinDS I just ran into this same issue this morning! Try this:

```ts
import * as matchers from '@testing-library/jest-dom/matchers';
import '@testing-library/jest-dom/vitest';
import { cleanup } from '@testing-library/react';
import { afterEach, expect } from 'vitest';

expect.extend(matchers);

afterEach(() => {
  cleanup();
});
```

**Comment by SidiEyel** [comment]
To make it work if you are using the vitest:

1. Make sure you have installed @testing-library/jest-dom
2. import '@testing-library/jest-dom/vitest' in test file for example > app.test.tsx import '@testing-library/jest-dom/vitest';

**Comment by JuanGidoni** [comment]
> To make it work if you are using the vitest:
> 
> 1. Make sure you have installed @testing-library/jest-dom
> 2. import '@testing-library/jest-dom/vitest' in test file for example > app.test.tsx import '@testing-library/jest-dom/vitest';

I created a `vitest.config.ts` file like mentioned before in the issue. I saw that if you import the `'@testing-library/jest-dom/vitest';` in the `vitest.config.ts` you avoid to always import the module one by one in your `.test`

I hope this helps 💪

**Comment by jonahallibone** [comment]
Wanna give this a bump, as this is still unresolved in my codebase (using the latest versions)

**Comment by jonahallibone** [comment]
> Wanna give this a bump, as this is still unresolved in my codebase (using the latest versions)

I actually resolved my issue. For those wondering, I had jest globals enabled in my project for some reason so i was never actually importing / using Vitest. I'd check to see if you're experiencing the same problem

**Comment by dteoh** [comment]
After upgrading Vitest to v2.1 and this lib to v6.6 I ran into this problem again. For reference I do not use vitest in globals mode, so more things broke after the upgrade.

This is what worked for me:

```ts
/// <reference types="@testing-library/jest-dom" />

import { expect } from "vitest";
import * as extensions from "@testing-library/jest-dom/matchers";
```

Importing the vitest sub-module of this library to augment TS just did not work for me.

**Comment by perkrlsn** [comment]
Ran into the same issue.

Create a `vitest.setup.ts` and add `import "@testing-library/jest-dom/vitest";` somewhere at the top of the file.

Include the file in your vitest config.

```typescript
export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: "vitest.setup.ts",
  },
});
```

To resolve type errors in your test files e.g.
```typescript
Property 'toBeInTheDocument' does not exist on type 'Assertion<HTMLElement>'.
```
 add `"@testing-library/jest-dom/vitest"` to your types in your tsconfig.

```typescript
...
"compilerOptions": {
  "types": ["@testing-library/jest-dom/vitest"],
},
...
```

**Comment by KumarVijayendra** [comment]
Only trouble I had was that I used to see red underlines in my editor for toBeInDocument or toHaveValue etc, as an error indicating:
```text
Property 'toBeInTheDocument' does not exist on type 'Assertion<HTMLElement>'.ts(2339)
```

Functionally tests were running fine.

I already had "vitest.setup.ts" with below import to extend capability of expect:
```js
import for @testing-library/jest-dom/vitest;
```
And my tsconfig.json was also updated with  
```js
{
	"compilerOptions": {
		...
		"types": ["@testing-library/jest-dom/vitest"],
		...
	},
	"include": ["src", "./vitest.setup.ts"],
	"exclude": ["node_modules"]
}
```

What fixed that tserror for me is updating mapped types in vitest.config.ts
from `/// <reference types="vitest/config" />`
to `/// <reference types="@testing-library/jest-dom/vitest" />`

**Comment by rik-iso** [comment]
I had to add `"@testing-library/jest-dom"` to my `types` in `tsconfig` as well. But still importing vitest in the actual code.
